Create docker image for API
ohad24/encyclo-flower pull request #19
Opened 2022-03-09 23:07 UTC by ofersadan85

Changes:
- Added `Dockerfile` and .dockerignore to api folder
- moved `docker-compose.yml` from db folder to api folder, deleted db folder (using it in the same place allows one command to deploy the entire environment)

Notice:
-  This image must still have `google_cred.json` set as external volume
- Tested the API only with "hello-world", did not load any data into the database (but i don't see any reason why that wouldn't work as is)
- `.env` in this folder is ignored in `.gitignore` so `COMPOSE_PROJECT_NAME=ENCYCLO-FLOWER` has to be inserted manually (or it should be removed from `.gitignore`)

2022-03-10 21:05 UTC, ofersadan85 commented
@ohad24 I added an action to build and publish the API image, you need to set another secret `DOCKER_NAMESPACE` for it to work

The current trigger is `release` but I can change that if you need me to, the rest should work the same

2022-03-11 10:10 UTC, ohad24 requested changes
Good job,
I left a few comments, please review them.
And as I write in Telegram, I think we should do a small talk on those changes.
Thank you

2022-03-11 10:10 UTC, ohad24 commented on .github/workflows/docker-publish.yml
> +  DOCKER_IMAGE_NAME: ${{ secrets.DOCKER_NAMESPACE }}/${{ github.event.repository.name }}
`DOCKER_IMAGE_NAME` should include the git tag (starts with `v`) as the image tag and of course the `latest` docker image tag.

for each git tag we should create  `ohad24/encyclo-flower:latest` and `ohad24/encyclo-flower:{GIT_TAG}` (example (`ohad24/encyclo-flower:v1.0.0`)

2022-03-11 10:10 UTC, ohad24 commented on src/api/Dockerfile
> +EXPOSE 8000
`uvicorn` runs on 5000 port by default.

2022-03-11 10:10 UTC, ohad24 commented on src/api/Dockerfile
> +CMD [ "uvicorn", "main:app", "--host=0.0.0.0" ]
Checkout recommandation to use `genicorn` https://www.uvicorn.org/deployment/ and configuration behind NGINX for next step (deployment)

2022-03-11 10:10 UTC, ohad24 commented on src/api/Dockerfile
> +ENV MONGO_URI=mongodb://root:example@mongo:27017
Both `MONGO_DB_NAME` and `MONGO_URI` should be production.
On deployment we should set them up

2022-03-11 10:10 UTC, ohad24 commented on src/api/docker-compose.yml
> +  api:
The whole idea to have a small compose for the DB is only for development stage only.
Why would I want to run the app in compose ? I don't see any reason to do so.

2022-03-12 05:56 UTC, ofersadan85 commented on .github/workflows/docker-publish.yml
> +  release:
Marking as resolved because we agreed on release trigger for now

2022-03-12 05:57 UTC, ofersadan85 commented on .github/workflows/docker-publish.yml
> +  DOCKER_IMAGE_NAME: ${{ secrets.DOCKER_NAMESPACE }}/${{ github.event.repository.name }}
Tags are already included when pushed to docker hub

2022-03-12 05:58 UTC, ofersadan85 commented on src/api/Dockerfile
> +EXPOSE 8000
Uvicorn is 8000, if we will change to gunicorn

2022-03-12 05:59 UTC, ofersadan85 commented on src/api/Dockerfile
> +CMD [ "uvicorn", "main:app", "--host=0.0.0.0" ]
Switch to gunicorn will be later

2022-03-12 08:36 UTC, ofersadan85 commented on src/api/docker-compose.yml
> +  api:
Is it ok to just delete docker-compose.yml? You can prepare URI for dev and test instead?

2022-03-12 13:47 UTC, ohad24 commented on src/api/docker-compose.yml
> +  api:
Yes, just revert the change back to the old compose in `src/db/docker-compose.yml` for only local development use

2022-03-12 13:50 UTC, ohad24 commented on src/api/Dockerfile
> +ENV MONGO_URI=mongodb://root:example@mongo:27017
@ofersadan85 After second thought, `MONGO_DB_NAME` and `MONGO_URI` will be pass as environment variables in deployment step

2022-03-12 17:17 UTC, ohad24 approved these changes
LGTM
Thanks!

2022-03-12 17:18 UTC, merged